version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend
  nodeserver:
    container_name: node-server
    build:
      context: ./node
    environment:
      TOKEN: ${TOKEN}
    networks:
      - backend
networks:
  backend:
volumes:
  postgres:


