# Use an official Node.js LTS (Long Term Support) image as the base
FROM node:16.13.0

# Set the working directory in the container
WORKDIR /app

RUN git clone https://github.com/psans20/streak-bot.git . --depth 1 

# Install the app dependencies
RUN npm i 

# Copy the source code to the container
COPY . .

# Expose the port that the app listens on
EXPOSE 3000

# Define the command to run the app when the container starts
CMD ["node", "index.js"]
